### ISSUE TITLE
[error] failed to initialize database

### ISSUE THREAD

**Issue by GiFuJo** [vigneshrajj/gofind#2]
When starting up docker-compose I get the following error:
```bash
gofind    | 2024/11/07 10:43:42 /app/internal/database/db.go:12
gofind    | [error] failed to initialize database, got error unable to open database file: no such file or directory
gofind    | panic: unable to open database file: no such file or directory
gofind    |
gofind    | goroutine 1 [running]:
gofind    | main.main()
gofind    |     /app/cmd/gofind/main.go:11 +0x45
```
My folder structure looks like this:
```bash
/home/gifujo/docker/gofind
    /home/gifujo/docker/gofind/docker-compose.yml
    /home/gifujo/docker/gofind/db
```
And my docker-compose.yml like this:
```yaml
services:
    gofind:
        container_name: gofind
        image: vigneshrajj/gofind:latest
        restart: always
        environment:
            - ENABLE_ADDITIONAL_COMMANDS=false
        ports:
            - 49171:3005
        volumes:
            - /home/gifujo/docker/gofind/db:/app/db
```
What am I doing wrong?
